# Generated by Django 5.1 on 2024-08-17 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscontent',
            old_name='punlish_time',
            new_name='published_time',
        ),
    ]
