# Generated by Django 5.1 on 2024-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'qabul qilindi'), ('rejected', 'rad etildi'), ('pending', 'kutilmoqda')], default='pending', max_length=16),
        ),
    ]
