# Generated by Django 5.1 on 2024-08-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi'), ('pending', 'Kutilmoqda')], default='pending', max_length=16),
        ),
    ]
